// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJSfxd-35aqqK9Y8iGyFlyFm7-4kOMjY',
    appId: '1:324605475240:web:8ae158d78266a263b6c59d',
    messagingSenderId: '324605475240',
    projectId: 'try-database-cf2f9',
    authDomain: 'try-database-cf2f9.firebaseapp.com',
    storageBucket: 'try-database-cf2f9.appspot.com',
    measurementId: 'G-2REQ54QV1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6h-tFm_P2eZMe_1ELwPaf8YTXfwarTp8',
    appId: '1:324605475240:android:e8be46625e055f73b6c59d',
    messagingSenderId: '324605475240',
    projectId: 'try-database-cf2f9',
    storageBucket: 'try-database-cf2f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKEmOD0tXXCb7nZ2EOGFkyKyHb6r11LA',
    appId: '1:324605475240:ios:cd27210fc151313bb6c59d',
    messagingSenderId: '324605475240',
    projectId: 'try-database-cf2f9',
    storageBucket: 'try-database-cf2f9.appspot.com',
    iosBundleId: 'com.example.onlypantsit14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxKEmOD0tXXCb7nZ2EOGFkyKyHb6r11LA',
    appId: '1:324605475240:ios:3325166f77576830b6c59d',
    messagingSenderId: '324605475240',
    projectId: 'try-database-cf2f9',
    storageBucket: 'try-database-cf2f9.appspot.com',
    iosBundleId: 'com.example.onlypantsit14.RunnerTests',
  );
}
