<script src="https://cdn.tailwindcss.com"></script>

<style>
    @media print {
        .print\:hidden {
            display: none;

        }

        @page {
            margin: 0;
        }

        /* Add more styling if needed */
        body {
            margin: 0;
            padding: 0;
        }
    }
</style>

<div class="py-12">
    <div class="max-w-7xl  mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden  sm:rounded-lg">

            <img class="mx-auto px-8 py-3 h-40 w-80" src="{{ asset('logo/tolentino-logo-pic.jpg') }}" alt="Logo">

            <div class="flex py-6 px-3">
                <div class="px-12">

                    <h2 class="font-bold">Client {{$data->client_id}}: {{$data->client_fname}} {{$data->client_mname}}
                        {{$data->client_sname}} case files.</h2>
                    <p class="text-1xl"> Slip generated by:
                        @php
                        $user = Auth::user()->name
                        @endphp
                        <?php echo $user;?>
                    </p>
                    <p class="text-1xl" id="dateParagraph">Date: </p>
                </div>
                <div class="ml-auto px-8 print:hidden">
                    <select name="status" id="status-filter" onchange="filterTable()">
                        <option value="">All</option>
                        <option value="Open">Open</option>
                        <option value="Closed">Closed</option>
                    </select>
                    <button
                        class="flex bg-purple-500 text-white px-7 py-2 rounded font-medium mx-1  hover:bg-purple-600 transition duration-200 each-in-out"
                        onclick="printPage()">
                        <p class="px-1">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z" />
                            </svg>

                        </p>
                        <p class="px-1"> Print</p>
                    </button>
                    <script>
                        function printPage() {
                            // Get the current date and time
                            var currentDate = new Date();
                            var formattedDate = currentDate.toLocaleDateString('en-US', {
                                year: 'numeric',
                                month: 'numeric',
                                day: 'numeric'
                            });
                            var formattedTime = currentDate.toLocaleTimeString('en-US', {
                                hour: 'numeric',
                                minute: 'numeric',
                                hour12: true
                            });

                            // Update the paragraph content
                            document.getElementById('dateParagraph').innerText = 'Date: ' + formattedDate + ', ' + formattedTime;

                            // Print the page
                            window.print();
                        }
                    </script>
                </div>
            </div>
            <div class="flex flex-col">
                <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
                    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="overflow-hidden">
                            <table class="min-w-full">
                                <thead class="bg-white border-b">
                                    <tr>
                                        <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                                            File ID #
                                        </th>
                                        <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                                            Case title
                                        </th>
                                        <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                                            Case type
                                        </th>
                                        <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                                            Status
                                        </th>
                                        <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                                            Case Remarks
                                        </th>
                                    </tr>
                                </thead>
                                <tbody id="file-table-body">
                                    @foreach($filedata as $row)
                                    <tr class="file-row bg-gray-100 border-b">
                                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                            {{$row->file_id}}
                                        </td>
                                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                            {{$row->file_name}}
                                        </td>
                                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                            {{$row->file_casetype}}
                                        </td>
                                        <td
                                            class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap file-status">
                                            {{$row->file_casestatus}}
                                        </td>
                                        <td
                                            class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap file-status">
                                            {{$row->file_remarks}}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <script>
                        function filterTable() {
                        var statusFilter = document.getElementById('status-filter').value;
                        var tableRows = document.querySelectorAll('.file-row');

                        tableRows.forEach(function(row) {
                            var statusCell = row.querySelector('.file-status');
                            var status = statusCell.textContent.trim();

                            if (statusFilter === '' || status === statusFilter || statusFilter === 'All') {
                                row.style.display = '';
                            } else {
                                row.style.display = 'none';
                            }
                        });
                    }
                    </script>
                </div>
            </div>
        </div>
    </div>
