// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsTbPUa97iWqW3s0DprNIjvB077NToZo',
    appId: '1:471853021830:web:bd3ba6a46f20f4f2076f07',
    messagingSenderId: '471853021830',
    projectId: 'fir-project1-e2a99',
    authDomain: 'fir-project1-e2a99.firebaseapp.com',
    storageBucket: 'fir-project1-e2a99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiFA-ONxPGpvKFevBYrXUNjItGxaGdwU',
    appId: '1:471853021830:android:3e0b08937911ee7b076f07',
    messagingSenderId: '471853021830',
    projectId: 'fir-project1-e2a99',
    storageBucket: 'fir-project1-e2a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSohg85HzVB8ZsKWNnKU_x_g8UkUug788',
    appId: '1:471853021830:ios:a4686b828ca74941076f07',
    messagingSenderId: '471853021830',
    projectId: 'fir-project1-e2a99',
    storageBucket: 'fir-project1-e2a99.appspot.com',
    iosClientId: '471853021830-akqecpatubbl5pg4n5u5cbdsl9afe6d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalprojectMl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSohg85HzVB8ZsKWNnKU_x_g8UkUug788',
    appId: '1:471853021830:ios:a4686b828ca74941076f07',
    messagingSenderId: '471853021830',
    projectId: 'fir-project1-e2a99',
    storageBucket: 'fir-project1-e2a99.appspot.com',
    iosClientId: '471853021830-akqecpatubbl5pg4n5u5cbdsl9afe6d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalprojectMl',
  );
}
